### ISSUE TITLE
3761 Firmware, would you happen to have it?

### ISSUE THREAD

**Issue by Swiftnesses** [mattmattandmatt/sky-sr102-router#1]
Hi Matt,

I've recently had to recover my SR102 due to it becoming non responsive. It appears the recovery tool uploaded a ridiculously old version of the firmware to the router - Sky say they cannot update it within the next few months! Would you happen to have a copy of the 3761 firmware which I could possible upload to the router using the web interface? A long shot I know, but I thought I'd ask...

Kind regards and happy christmas,

Mark

**Comment by mattmattandmatt** [comment]
Unfortunately not.  From what I can tell... that old one is the _only_ one
which will work (without using serial or jtag)

**Comment by intotheunknown1997** [comment]
this worked really good and it worked with serial if you want to remotely assess the router though telnet you have to first have a serial connected. login into the router by serial and run the shell command `sh`  since its Linux, busybox is installed you can run `busybox telnetd` 

is there any way to put this command in the startup so i don't have to have serial connected to test some new programs thanks.

**Comment by mattmattandmatt** [comment]
`telnetd` already runs at (sort of) startup. It is set in the `buildconfig.cfg` file.

**Comment by intotheunknown1997** [comment]
ok thanks
