### ISSUE TITLE
How To Install ER115 ToolChain

### ISSUE THREAD

**Issue by Shoaib7359** [mattmattandmatt/sky-sr102-router#11]
can i use another isp On Sky ER115 By Modifying Firmware

**Comment by mattmattandmatt** [comment]
errrmmmm...  well very small amount of isp's will let the sky router work without modifying it.  But I don't know how to modify the ER115 firmware because my bootloader is locked.  I don't know how to unlock it without changing the flash chip completely.
I have found a way to access the shell - but you loose everything the next time you reboot.

**Comment by Shoaib7359** [comment]
i we have source firmware and toolchain then

**Comment by Shoaib7359** [comment]
and if i change the flash chip then what is the procedure

**Comment by mattmattandmatt** [comment]
If you can change the flash chip.  Then I am assuming you can recompiling the source code:
http://www1.sky.com/opensourcesoftware/SkyQ/SkyQHub/SkyQHub_downloads.html
I recommend using a 32bit version of Linux.  So you don't run into FakeRoot problems.

Because I have not replaced the chip, I have not written any procedure.
Other info:
https://github.com/mattmattandmatt/sky-sr102-router/issues/6

**Comment by mattmattandmatt** [comment]
Here is a link to the original firmwares/bootloader/info I saved for the ER115 router.  It might be useful for someone.
https://drive.google.com/drive/folders/14_csix1Buu2U0npzytqnIbIi5TwMBbGi
